 export const data=[{
    img:'https://cdn.getyourguide.com/img/mic/crop-tour-277-5c050167dc978.jpeg/wide_320_uncropped_q50.webp',
    symbol:"",
    header:"From Lasvegas: Grand canyon tour with helicopter with champane",
    pickup:true,
    duration:"4 hours",
    stars:"4.9",
    reviews:"100",
    button:"Adventure",
    buttonColour:'#FF7083',
    skipTheline:false,
    price:"$234",
},{
    img:'https://cdn.getyourguide.com/img/mic/crop-tour-277-5f044ab13139b.jpeg/wide_320_uncropped_q50.webp',
    symbol:"",
    header:"From Lasvegas: Grand canyon tour with helicopter with champane",
    pickup:true,
    duration:"4 hours",
    stars:"4.2",
    reviews:"100",
    button:"Adventure",
    buttonColour:'teal',
    skipTheline:false,
    price:"$233",
},{
    img:'https://cdn.getyourguide.com/img/mic/crop-tour-277-60562de565d7b.jpeg/wide_320_uncropped_q50.webp',
    symbol:"",
    header:"From Lasvegas: Grand canyon tour with helicopter with champane",
    pickup:true,
    duration:"4 hours",
    stars:"4.9",
    reviews:"100",
    button:"Adventure",
    buttonColour:'#1593FF',
    skipTheline:false,
    price:"$234",
},{
    img:'https://cdn.getyourguide.com/img/mic/crop-tour-277-a161e9a60b0847f3.jpeg/wide_320_uncropped_q50.webp',
    symbol:"",
    header:"From Lasvegas: Grand canyon tour with helicopter with champane",
    pickup:true,
    duration:"4 hours",
    stars:"4",
    reviews:"100",
    button:"Adventure",
    buttonColour:'#FF7083',
    skipTheline:false,
    price:"$544",
},{
    img:'https://cdn.getyourguide.com/img/mic/crop-tour-277-60562de565d7b.jpeg/wide_320_uncropped_q50.webp',
    symbol:"",
    header:"From Lasvegas: Grand canyon tour with helicopter with champane",
    pickup:true,
    duration:"4 hours",
    stars:"4.9",
    reviews:"100",
    button:"Adventure",
    buttonColour:'#FF7083',
    skipTheline:false,
    price:"$234",
},{
    img:'https://cdn.getyourguide.com/img/mic/crop-tour-277-a161e9a60b0847f3.jpeg/wide_320_uncropped_q50.webp',
    symbol:"",
    header:"From Lasvegas: Grand canyon tour with helicopter with champane",
    pickup:true,
    duration:"4 hours",
    stars:"4.2",
    reviews:"100",
    button:"Adventure",
    buttonColour:'teal',
    skipTheline:false,
    price:"$233",
},{
    img:'https://cdn.getyourguide.com/img/mic/crop-tour-277-5cdf0a98ed191.jpeg/wide_320_uncropped_q50.webp',
    symbol:"",
    header:"From Lasvegas: Grand canyon tour with helicopter with champane",
    pickup:true,
    duration:"4 hours",
    stars:"2.5",
    reviews:"100",
    button:"Adventure",
    buttonColour:'#1593FF',
    skipTheline:false,
    price:"$294",
},
{
    img:'https://cdn.getyourguide.com/img/mic/crop-tour-277-a161e9a60b0847f3.jpeg/wide_320_uncropped_q50.webp',
    symbol:"",
    header:"From Lasvegas: Grand canyon tour with helicopter with champane",
    pickup:true,
    duration:"4 hours",
    stars:"4.2",
    reviews:"100",
    button:"Adventure",
    buttonColour:'teal',
    skipTheline:false,
    price:"$293",
},{
    img:'https://cdn.getyourguide.com/img/mic/crop-tour-277-60562de565d7b.jpeg/wide_320_uncropped_q50.webp',
    symbol:"",
    header:"From Lasvegas: Grand canyon tour with helicopter with champane",
    pickup:true,
    duration:"4 hours",
    stars:"4",
    reviews:"900",
    button:"Adventure",
    buttonColour:'#FF7083',
    skipTheline:false,
    price:"$644",
},{
    img:'https://cdn.getyourguide.com/img/mic/crop-tour-277-60562de565d7b.jpeg/wide_320_uncropped_q50.webp',
    symbol:"",
    header:"From Lasvegas: Grand canyon tour with helicopter with champane",
    pickup:true,
    duration:"4 hours",
    stars:"4.9",
    reviews:"100",
    button:"Adventure",
    buttonColour:'#1593FF',
    skipTheline:false,
    price:"$234",
}]